/** Declaration file generated by dts-gen */

export function hasOwn(t: any, h: any): void;

export function hasOwnProperty(p0: any): any;

export function isArray(p0: any): any;

export function isAsync(t: any): void;

export function isBigInt(t: any): void;

export function isBoolean(t: any): void;

export function isDate(t: any): void;

export function isFunction(t: any): void;

export function isMap(t: any): void;

export function isNullOrUndefined(t: any): void;

export function isNumber(t: any): void;

export function isObject(t: any): void;

export function isPromise(t: any): void;

export function isRegExp(t: any): void;

export function isSet(t: any): void;

export function isString(t: any): void;

export function isSymbol(t: any): void;

export function toTypeString(t: any): void;

export function typeName(t: any): void;

